//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using BusinessEntities;
    
    public partial class LABASPRODENTConnection : DbContext
    {
        public LABASPRODENTConnection()
            : base("name=LABASPRODENTConnection")
        {
    		this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DetallesOrdens> DetallesOrdens { get; set; }
        public virtual DbSet<EstadosOrdenes> EstadosOrdenes { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<Insumos> Insumos { get; set; }
        public virtual DbSet<InsumosCompras> InsumosCompras { get; set; }
        public virtual DbSet<InsumosProcesos> InsumosProcesos { get; set; }
        public virtual DbSet<Ordenes> Ordenes { get; set; }
        public virtual DbSet<Procesos> Procesos { get; set; }
        public virtual DbSet<ProcesosProductos> ProcesosProductos { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<TiposClientes> TiposClientes { get; set; }
        public virtual DbSet<TiposOrdenes> TiposOrdenes { get; set; }
        public virtual DbSet<TransicionesOrdenes> TransicionesOrdenes { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
    }
}
