//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesOrdens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetallesOrdens()
        {
            this.TransicionesOrdenes = new HashSet<TransicionesOrdenes>();
        }
    
        public int IdDetalleOrden { get; set; }
        public Nullable<int> FkIdOrden { get; set; }
        public Nullable<int> FkIdProducto { get; set; }
        public string Prioridad { get; set; }
        public Nullable<System.DateTime> FechaEstimadaEntrega { get; set; }
    
        public virtual Ordenes Ordenes { get; set; }
        public virtual Productos Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransicionesOrdenes> TransicionesOrdenes { get; set; }
    }
}
