//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int IdFactura { get; set; }
        public int FkIdOrden { get; set; }
        public System.DateTime FechaFactura { get; set; }
        public decimal Abono { get; set; }
        public decimal ValorTotalFactura { get; set; }
    
        public virtual Ordenes Ordenes { get; set; }
    }
}
