//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsumosProcesos
    {
        public int IdInsumoProceso { get; set; }
        public int FkIdProceso { get; set; }
        public int FkIdInsumo { get; set; }
        public decimal Cantidad { get; set; }
        public string Unidad { get; set; }
    
        public virtual Insumos Insumos { get; set; }
        public virtual Procesos Procesos { get; set; }
    }
}
