//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsumosCompras
    {
        public int IdInsumosCompras { get; set; }
        public int FkIdInsumo { get; set; }
        public int FkIdProveedor { get; set; }
        public decimal Cantidad { get; set; }
        public int CostoUnidad { get; set; }
        public int CostoTotal { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public Nullable<System.DateTime> FechaFinalInsumo { get; set; }
    
        public virtual Insumos Insumos { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
