//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransicionesOrdenes
    {
        public int IdTransicion { get; set; }
        public int FkIdDetalleOrden { get; set; }
        public int FkIProcesoProducto { get; set; }
        public int FkIdEmpleadoAcargo { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaTransicion { get; set; }
    
        public virtual DetallesOrdens DetallesOrdens { get; set; }
        public virtual ProcesosProductos ProcesosProductos { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
